image: docker:latest

stages:
  - build
  - push
  - deploy

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

build_backend:
  stage: build
  script:
    - docker build -t $DOCKER_USERNAME/sesi9_backend:$CI_COMMIT_REF_NAME -f backend/Dockerfile backend
    - docker push $DOCKER_USERNAME/sesi9_backend:$CI_COMMIT_REF_NAME
  only:
    - main
